spring:
  application:
    name: sbb

  profiles:
    active: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/local
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
